import { app, Tray, Menu, nativeImage, BrowserWindow, ipcMain, globalShortcut } from "electron";
import { getHotkeyManager } from "./main/hotkey";
import { transcribe } from "./main/transcription";
import { formatText } from "./main/formatting";
import { pasteText, checkAccessibilityPermission, requestAccessibilityPermission } from "./main/paste";
import store from "./main/store";
import * as fs from "fs";
import * as path from "path";
import "dotenv/config";

// Webpack entry point declarations (auto-generated by Forge's Webpack plugin)
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

let tray: Tray | null = null;
let settingsWindow: BrowserWindow | null = null;
let recorderWindow: BrowserWindow | null = null;

// --- App State ---
type AppState = "idle" | "recording" | "processing";
let currentState: AppState = "idle";

// --- Tray Icon Creation (using PNG files for reliability) ---

// Get the path to icon files
function getIconPath(state: AppState): string {
  const iconName = `tray-${state}.png`;
  // Assets are copied to 'assets' folder in webpack output
  return path.join(__dirname, "assets", iconName);
}

function createTrayIcon(state: AppState): Electron.NativeImage {
  const iconPath = getIconPath(state);
  const image = nativeImage.createFromPath(iconPath);

  if (image.isEmpty()) {
    console.error(`[StayFree] ERROR: Icon not found at: ${iconPath}`);
  }

  // For idle state, mark as template so macOS can adapt to dark/light mode
  if (state === "idle") {
    image.setTemplateImage(true);
  }

  return image;
}

function updateTrayState(state: AppState): void {
  currentState = state;
  if (tray) {
    tray.setImage(createTrayIcon(state));
    tray.setToolTip(
      state === "idle"
        ? "StayFree - Ready (Hold Fn to dictate)"
        : state === "recording"
          ? "StayFree - Recording..."
          : "StayFree - Processing...",
    );
  }
}

// Export for use by other modules later
export { updateTrayState, currentState };
export type { AppState };

// --- Context Menu ---

function buildContextMenu(): Menu {
  return Menu.buildFromTemplate([
    {
      label: `StayFree v${app.getVersion()}`,
      enabled: false,
    },
    { type: "separator" },
    {
      label: "Paste Last Transcript",
      accelerator: "Ctrl+Cmd+V",
      click: async () => {
        const lastTranscript = store.get("lastTranscript") as string;
        if (lastTranscript) {
          await pasteText(lastTranscript);
        }
      },
    },
    { type: "separator" },
    {
      label: "Settings...",
      accelerator: "Cmd+,",
      click: () => {
        openSettingsWindow();
      },
    },
    { type: "separator" },
    {
      label: "Quit StayFree",
      accelerator: "Cmd+Q",
      click: () => {
        app.quit();
      },
    },
  ]);
}

// --- Recorder Window (Hidden) ---

function createRecorderWindow(): void {
  recorderWindow = new BrowserWindow({
    width: 400,
    height: 300,
    show: false, // Hidden window
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  recorderWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  recorderWindow.on("closed", () => {
    recorderWindow = null;
  });

  console.log("[StayFree] Hidden recorder window created");
}

// --- Settings Window ---

function openSettingsWindow(): void {
  if (settingsWindow) {
    settingsWindow.focus();
    return;
  }

  settingsWindow = new BrowserWindow({
    width: 480,
    height: 520,
    title: "StayFree Settings",
    resizable: false,
    minimizable: false,
    maximizable: false,
    fullscreenable: false,
    show: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  settingsWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  settingsWindow.once("ready-to-show", () => {
    settingsWindow.show();
  });

  settingsWindow.on("closed", () => {
    settingsWindow = null;
  });
}

// --- App Lifecycle ---

app.on("ready", () => {
  // Hide dock icon on macOS - this is a tray-only app
  if (process.platform === "darwin") {
    app.dock.hide();
  }

  // Check accessibility permission on startup (needed for auto-paste)
  if (!checkAccessibilityPermission()) {
    requestAccessibilityPermission();
  }

  // Create system tray
  tray = new Tray(createTrayIcon("idle"));
  tray.setContextMenu(buildContextMenu());
  tray.setToolTip("StayFree - Ready (Hold Fn to dictate)");

  console.log(
    "[StayFree] Running in system tray. Right-click tray icon for menu.",
  );

  // Create hidden recorder window (for Web Audio API access)
  createRecorderWindow();

  // Initialize hotkey manager (Fn key for push-to-talk)
  const hotkeyManager = getHotkeyManager({ useFnKey: true });

  hotkeyManager.on("recording-start", () => {
    console.log("[Main] Hotkey pressed - starting recording");
    updateTrayState("recording");

    // Tell recorder window to start capturing audio
    if (recorderWindow) {
      recorderWindow.webContents.send("start-recording");
    }
  });

  hotkeyManager.on("recording-stop", () => {
    console.log("[Main] Hotkey released - stopping recording");
    updateTrayState("idle");

    // Tell recorder window to stop and send audio
    if (recorderWindow) {
      recorderWindow.webContents.send("stop-recording");
    }
  });

  // Start listening for hotkeys
  hotkeyManager.start();

  // Register fallback hotkey: Ctrl+Cmd+V pastes last transcript
  globalShortcut.register("Ctrl+Cmd+V", async () => {
    const lastTranscript = store.get("lastTranscript") as string;
    if (lastTranscript) {
      console.log("[Main] Fallback hotkey: pasting last transcript");
      const pasted = await pasteText(lastTranscript);
      if (!pasted) {
        console.error("[Main] Fallback paste failed");
      }
    } else {
      console.log("[Main] Fallback hotkey: no last transcript to paste");
    }
  });

  // IPC Handler: Receive audio blob from renderer
  ipcMain.on("audio-captured", async (_event, audioData: Buffer) => {
    console.log(`[Main] Received audio data: ${audioData.length} bytes`);

    // Update tray to processing state
    updateTrayState("processing");

    // Save audio for debugging (optional)
    const recordingsDir = path.join(__dirname, "..", "..", "recordings");
    if (!fs.existsSync(recordingsDir)) {
      fs.mkdirSync(recordingsDir, { recursive: true });
    }
    const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
    const audioPath = path.join(recordingsDir, `recording-${timestamp}.webm`);
    fs.writeFileSync(audioPath, audioData);
    console.log(`[Main] Audio saved: ${audioPath}`);

    // Transcribe audio using Groq Whisper API
    const transcript = await transcribe(audioData);

    if (transcript) {
      console.log(`[Main] ✓ Transcript: "${transcript}"`);

      // Format text: punctuation + voice commands + dictionary replacements
      const formattedText = await formatText(transcript);
      console.log(`[Main] ✓ Formatted: "${formattedText}"`);

      // Store for fallback paste
      store.set("lastTranscript", formattedText);

      // Auto-paste into active app
      const pasted = await pasteText(formattedText);
      if (!pasted) {
        console.error("[Main] Auto-paste failed - text is in clipboard, user can Cmd+V manually");
      }
    } else {
      console.error("[Main] Transcription failed");
    }

    // Return to idle state
    updateTrayState("idle");
  });
});

// Tray app: keep running when all windows closed
app.on("window-all-closed", () => {
  // Do nothing - app lives in tray, not in windows
});

app.on("before-quit", () => {
  // Unregister global shortcuts
  globalShortcut.unregisterAll();

  // Stop hotkey listener
  const hotkeyManager = getHotkeyManager();
  hotkeyManager.stop();

  if (tray) {
    tray.destroy();
    tray = null;
  }
});
