import { app, Tray, Menu, nativeImage, BrowserWindow } from "electron";

// Webpack entry point declarations (auto-generated by Forge's Webpack plugin)
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

let tray: Tray | null = null;
let settingsWindow: BrowserWindow | null = null;

// --- App State ---
type AppState = "idle" | "recording" | "processing";
let currentState: AppState = "idle";

// --- Tray Icon Creation (using PNG files for reliability) ---

import * as path from "path";

// Get the path to icon files
function getIconPath(state: AppState): string {
  const iconName = `tray-${state}.png`;
  // Assets are copied to 'assets' folder in webpack output
  return path.join(__dirname, "assets", iconName);
}

function createTrayIcon(state: AppState): Electron.NativeImage {
  const iconPath = getIconPath(state);
  console.log(`[StayFree] Loading icon from: ${iconPath}`);

  const image = nativeImage.createFromPath(iconPath);

  if (image.isEmpty()) {
    console.error(`[StayFree] ERROR: Icon not found at: ${iconPath}`);
  } else {
    console.log(
      `[StayFree] Icon loaded: ${image.getSize().width}x${image.getSize().height}`,
    );
  }

  // For idle state, mark as template so macOS can adapt to dark/light mode
  if (state === "idle") {
    image.setTemplateImage(true);
  }

  return image;
}

function updateTrayState(state: AppState): void {
  currentState = state;
  if (tray) {
    tray.setImage(createTrayIcon(state));
    tray.setToolTip(
      state === "idle"
        ? "StayFree - Ready (Hold Fn to dictate)"
        : state === "recording"
          ? "StayFree - Recording..."
          : "StayFree - Processing...",
    );
  }
}

// Export for use by other modules later
export { updateTrayState, currentState };
export type { AppState };

// --- Context Menu ---

function buildContextMenu(): Menu {
  return Menu.buildFromTemplate([
    {
      label: `StayFree v${app.getVersion()}`,
      enabled: false,
    },
    { type: "separator" },
    {
      label: "Paste Last Transcript",
      accelerator: "Ctrl+Cmd+V",
      click: () => {
        // TODO: Phase 6 - paste last transcript functionality
        console.log("[StayFree] Paste last transcript clicked");
      },
    },
    { type: "separator" },
    {
      label: "Settings...",
      accelerator: "Cmd+,",
      click: () => {
        openSettingsWindow();
      },
    },
    { type: "separator" },
    {
      label: "Quit StayFree",
      accelerator: "Cmd+Q",
      click: () => {
        app.quit();
      },
    },
  ]);
}

// --- Settings Window ---

function openSettingsWindow(): void {
  if (settingsWindow) {
    settingsWindow.focus();
    return;
  }

  settingsWindow = new BrowserWindow({
    width: 480,
    height: 520,
    title: "StayFree Settings",
    resizable: false,
    minimizable: false,
    maximizable: false,
    fullscreenable: false,
    show: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  settingsWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  settingsWindow.once("ready-to-show", () => {
    settingsWindow.show();
  });

  settingsWindow.on("closed", () => {
    settingsWindow = null;
  });
}

// --- App Lifecycle ---

app.on("ready", () => {
  // Hide dock icon on macOS - this is a tray-only app
  if (process.platform === "darwin") {
    app.dock.hide();
  }

  // Create system tray
  tray = new Tray(createTrayIcon("idle"));
  tray.setContextMenu(buildContextMenu());
  tray.setToolTip("StayFree - Ready (Hold Fn to dictate)");

  console.log(
    "[StayFree] Running in system tray. Right-click tray icon for menu.",
  );
});

// Tray app: keep running when all windows closed
app.on("window-all-closed", () => {
  // Do nothing - app lives in tray, not in windows
});

app.on("before-quit", () => {
  if (tray) {
    tray.destroy();
    tray = null;
  }
});
