import {
  app,
  Tray,
  Menu,
  nativeImage,
  BrowserWindow,
  ipcMain,
  globalShortcut,
  systemPreferences,
  shell,
  screen,
} from "electron";
import { getHotkeyManager } from "./main/hotkey";
import { getWhisperServer } from "./main/whisper/server";
import { transcribePcm, PipelineError } from "./main/whisper/transcriber";
import { pasteText } from "./main/paste";
import store, { TranscriptionEntry, purgeLegacySarvamApiKey, seedWordCountFromHistory } from "./main/store";
import {
  saveAudioFile,
  deleteAudioFile,
  cleanupAllAudioFiles,
  copyAudioToDownloads,
} from "./main/storage";
import {
  isMac,
  isWindows,
  fallbackPasteShortcut,
  holdKeyLabel,
  pasteShortcutLabel,
  quitShortcut,
  settingsShortcut,
} from "./main/platform";
import * as path from "path";
import { spawn, ChildProcess } from "child_process";
import * as fs from "fs";

// Webpack entry point declarations (auto-generated by Forge's Webpack plugin)
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

// `electron-forge start` runs the generic Electron.app bundle. Override the
// visible development identity while keeping the packaged bundle metadata
// controlled by forge.config.ts.
if (isMac) {
  app.setName("StayFree");
}

let tray: Tray | null = null;
let settingsWindow: BrowserWindow | null = null;
let recorderWindow: BrowserWindow | null = null;
let onboardingWindow: BrowserWindow | null = null;
let widgetWindow: BrowserWindow | null = null;

interface AudioStreamStatsPayload {
  chunkCount: number;
  pcmBytes: number;
  avgRms: number;
  maxRms: number;
  baselineRms: number;
  voicedMs: number;
  hasSpeech: boolean;
  isBorderlineSpeech: boolean;
  streamingFailed: boolean;
}

interface RecordingSession {
  sessionId: string;
  startTs: number;
  stopTs: number | null;
  pcmChunks: Buffer[];
  chunkCount: number;
  chunkBytes: number;
  energySummary: AudioStreamStatsPayload | null;
  pipelineId: number | null;
  pipelineTimer: ReturnType<typeof setTimeout> | null;
}

/** Safety net: max time the app can stay in "processing" state before
 * force-reset. 12s (was 20s — FIX 8, 2026-07-30): the engine is local
 * (measured ASR 0.15-1.2s), and the worst legitimate chain — a hung-server
 * self-heal (attempt 1 timeout ~8.5s + instant-SIGKILL restart ~1s +
 * attempt 2 ~1s ≈ 11s) — still fits. Stale retries/restarts after this
 * deadline are blocked by transcribePcm's shouldContinue callback. */
const PROCESSING_TIMEOUT_MS = 12_000;

// Prevent duplicate app instances (and duplicate tray icons).
const gotSingleInstanceLock = app.requestSingleInstanceLock();
if (!gotSingleInstanceLock) {
  app.quit();
}

// --- Global error handler: prevent native Electron crash dialog ---
process.on("uncaughtException", (error) => {
  console.error("[Main] Uncaught exception (handled gracefully):", error);
  // If we're stuck in processing state due to the error, force reset
  if (isProcessing) {
    console.warn("[Main] Force-resetting processing state after uncaught exception");
    // No in-flight network operation to abort here: transcribePcm()'s own
    // AbortController self-terminates within ASR_REQUEST_TIMEOUT_MS
    // regardless of this reset, and its result is discarded by the stale
    // activePipelineId check below once it settles.
    activePipelineId = null;
    isProcessing = false;
    activeRecordingSource = null;
    clearRecordingSession();
    if (processingTimer) {
      clearTimeout(processingTimer);
      processingTimer = null;
    }
    updateTrayState("idle");
    sendWidgetState("idle");
  }
});

// --- App State ---
type AppState = "idle" | "recording" | "processing";
let currentState: AppState = "idle";
let isProcessing = false; // Guard against concurrent pipeline runs
let processingTimer: ReturnType<typeof setTimeout> | null = null; // Failsafe timer
let pipelineSequence = 0;
let activePipelineId: number | null = null;
type RecordingSource = "hotkey" | "widget" | null;
let activeRecordingSource: RecordingSource = null;
let lastRecordingSource: RecordingSource = null;
let activeRecordingSession: RecordingSession | null = null;

type WidgetUiState =
  | "idle"
  | "recording-hotkey"
  | "recording-click"
  | "processing"
  | "error";

/** Typed widget-state IPC payload (D1) — replaces the old bare-string
 * channel. `pipelineId` mirrors the main-side `activePipelineId` guard so a
 * stale pipeline's error can never be sent for a superseded recording (every
 * call site below only sends "error" when `activePipelineId === pipelineId`,
 * same check already used for every other end-of-pipeline reset).
 * `pipelineId` is informational for the renderer (a future error-UI PR may
 * use it); the renderer does not read it today — staleness is enforced
 * main-side, which is sufficient. */
interface WidgetStatePayload {
  state: WidgetUiState;
  message?: string;
  pipelineId?: number | null;
}
// The floating widget lives inside ONE fixed-size, never-resized native window.
// All shape/size changes between idle/recording/processing happen in CSS inside
// this window (see widget.css) so the native frame never animates — that native
// setBounds animation was the source of the visible glitch. The window is sized
// large enough to hold the biggest pill state with a little breathing room.
const WIDGET_WINDOW_WIDTH = 260;
// The window is intentionally TALL. macOS refuses to position a window with its
// top edge below ~y=717 (it clamps it out of the dock's reserved zone), so a
// short 56px window could never sit flush at the screen bottom in a fullscreen
// Space. A tall window's top stays above that line, so its bottom edge is free
// to reach the very bottom of the screen. The pill is anchored to the window's
// bottom via CSS; everything outside the pill's own rect is transparent AND
// click-through (see the hit-test poller below), so the extra height is
// invisible and inert.
const WIDGET_WINDOW_HEIGHT = 140;

// ============================================================================
// Widget click-through hit-testing (main-process owned)
// ============================================================================
//
// WHY this lives in main and not in the renderer:
//
// The widget's native window is 260x140 but the visible idle pill is only 40x8.
// The window must therefore be click-through by default so the user can keep
// using whatever app sits behind it. The old mechanism let the RENDERER decide:
// a large invisible `.widget-hit` div (236x46) carried onMouseEnter/onMouseLeave
// which toggled setIgnoreMouseEvents. That had three problems:
//
//   1. The hover target was the div, not the pill — so a ~98px-wide invisible
//      dead band on each side of the 40px idle pill silently swallowed clicks
//      meant for the app underneath.
//   2. `repositionWidget()` tweens the window's Y when the dock shows/hides. If
//      the window slid out from under a stationary cursor, no `mouseleave` ever
//      fired, so click-through stayed OFF forever — a permanent dead zone.
//   3. If the widget renderer reloaded or crashed while click-through was OFF,
//      main never learned about it and never reset the flag.
//
// Polling the real cursor position against the pill's real rect in main fixes
// all three at once: every tick re-reads `getBounds()` fresh, so a repositioned
// (or fullscreen-Space-relocated) window self-heals on the very next tick, and
// a renderer reload/crash cannot leave a stale interactive state behind because
// the renderer is no longer part of the decision at all.
const WIDGET_HIT_POLL_MS = 50;

// Extra margin grown on all sides of the pill rect. An 8px-tall idle pill is a
// brutal hover target, so this buys back comfort without recreating the old
// dead band: idle becomes ~52x20 instead of the old 236x46 (~20x smaller).
// It also covers framer's `whileHover` scaleX 1.08 on the idle pill, which
// visually widens 40px -> ~43.2px (1.6px per side). Don't grow this past 6px
// without a concrete reason — every px here is dead space for the app behind.
const PILL_HIT_PADDING = 6;

// The pill sits 8px above the window's bottom edge. That 8px is the
// `.widget-hit { padding-bottom: 8px }` rule in widget.css — if that value ever
// changes, this must change with it.
const PILL_BOTTOM_OFFSET = 8;

// Pill size per widget state, in CSS px.
//
// !!! KEEP IN SYNC with `pillVariants` in src/renderer/widget/App.tsx !!!
// The renderer owns the animation (framer springs morph between these sizes);
// main owns the hit-test and only needs the target geometry. There is no way to
// share one table across the process boundary without an IPC round-trip on
// every state change, so the two tables are duplicated deliberately.
const PILL_SIZES: Record<WidgetUiState, { width: number; height: number }> = {
  idle: { width: 40, height: 8 },
  "recording-hotkey": { width: 74, height: 30 },
  "recording-click": { width: 108, height: 30 },
  processing: { width: 48, height: 30 },
  error: { width: 56, height: 30 },
};

// What the renderer is currently showing, tracked so the poller can pick the
// right pill size. Updated at the actual `webContents.send("widget-state")`
// call sites in sendWidgetState() — not at its entry — because that function
// can DEFER an idle send (MIN_PROCESSING_VISIBLE_MS), and tracking the deferred
// send early would shrink the hit rect while the processing pill is still up.
//
// Known, accepted mismatch — the error pill: the renderer owns a 3000ms
// ERROR_VISIBLE_MS timer and deliberately ignores main's routine "idle" reset
// while it runs, so for up to 3s main hit-tests the 40x8 idle rect while a
// 56x30 error pill is on screen. That is safe: the tracked rect is SMALLER than
// what's drawn (never a phantom dead zone), the error pill has no click
// handlers, and it self-corrects the moment the timer fires. Mirroring the
// renderer's timer here would mean duplicating ERROR_VISIBLE_MS across the
// process boundary and interleaving a second timer with the existing
// widgetPendingIdleTimer machinery — more sync surface than the bug is worth.
// The only hard requirement is that main can never get STUCK on a large rect,
// and it can't: every `sendWidgetState("error")` call site is immediately
// followed by a `sendWidgetState("idle")` under the same guard.
let currentWidgetUiState: WidgetUiState = "idle";

// Mirrors the window's actual setIgnoreMouseEvents value so the poller only
// calls into Electron on a real transition instead of 20x/second.
let widgetIgnoresMouse = true;
let widgetHitPollTimer: ReturnType<typeof setInterval> | null = null;

/** The pill's rect in GLOBAL screen coordinates, already padded.
 * `getBounds()` is global screen coords and so is `screen.getCursorScreenPoint()`,
 * so no workArea/display offset conversion belongs anywhere in here — mixing one
 * in would break the moment a second display exists. */
function getPaddedPillScreenRect(bounds: Electron.Rectangle): {
  left: number;
  right: number;
  top: number;
  bottom: number;
} {
  // Use the TARGET state's size immediately on a state change. The pill spends
  // ~200-300ms springing between sizes, so the rect briefly disagrees with what
  // is drawn; that's fine and far simpler than tracking the animation.
  const pill = PILL_SIZES[currentWidgetUiState];

  // Bottom-anchored, horizontally centred inside the window (widget.css:
  // .widget-root centres .widget-hit, which centres the pill and pads it 8px
  // off the bottom).
  const bottom = bounds.y + bounds.height - PILL_BOTTOM_OFFSET;
  const top = bottom - pill.height;
  const left = bounds.x + Math.round((bounds.width - pill.width) / 2);
  const right = left + pill.width;

  return {
    left: left - PILL_HIT_PADDING,
    right: right + PILL_HIT_PADDING,
    top: top - PILL_HIT_PADDING,
    bottom: bottom + PILL_HIT_PADDING,
  };
}

function setWidgetIgnoresMouse(ignore: boolean): void {
  if (!widgetWindow || widgetWindow.isDestroyed()) return;
  if (widgetIgnoresMouse === ignore) return;
  widgetIgnoresMouse = ignore;
  // Plain `true` — NO `{ forward: true }`. Forwarding existed only so the old
  // renderer-side hover handlers could see mousemove through a click-through
  // window; main does its own hit-testing now, so forwarding would just be
  // pointless event traffic (and a source of stale renderer hover states).
  widgetWindow.setIgnoreMouseEvents(ignore);
}

function startWidgetHitPoll(): void {
  if (widgetHitPollTimer) return;
  widgetHitPollTimer = setInterval(() => {
    if (!widgetWindow || widgetWindow.isDestroyed()) return;

    // Hidden window: drive toward click-through rather than skipping the tick.
    // Skipping would freeze whatever value was last set, which is exactly the
    // "stuck interactive" failure this rewrite exists to kill.
    if (!widgetWindow.isVisible()) {
      setWidgetIgnoresMouse(true);
      return;
    }

    // Fresh bounds EVERY tick — this is what makes the reposition tween (dock
    // show/hide) and fullscreen-Space moves self-heal with no special-casing.
    const rect = getPaddedPillScreenRect(widgetWindow.getBounds());
    const cursor = screen.getCursorScreenPoint();
    const overPill =
      cursor.x >= rect.left &&
      cursor.x <= rect.right &&
      cursor.y >= rect.top &&
      cursor.y <= rect.bottom;

    setWidgetIgnoresMouse(!overPill);
  }, WIDGET_HIT_POLL_MS);
}

function stopWidgetHitPoll(): void {
  if (widgetHitPollTimer) {
    clearInterval(widgetHitPollTimer);
    widgetHitPollTimer = null;
  }
}

// --- Tray Icon Creation (using PNG files for reliability) ---

// Get the path to icon files
function getIconPath(): string {
  const iconName = "trayIcon.png";
  // Assets are copied to 'assets' folder in webpack output
  return path.join(__dirname, "assets", iconName);
}

function createTrayIcon(): Electron.NativeImage {
  const iconPath = getIconPath();
  const image = nativeImage.createFromPath(iconPath);

  if (image.isEmpty()) {
    console.error(`[StayFree] ERROR: Icon not found at: ${iconPath}`);
  }

  // Full-color icon (cream tile + ink bars) — must NOT be a template image,
  // or macOS would flatten it to monochrome menu-bar tint.
  image.setTemplateImage(false);

  return image;
}

function updateTrayState(state: AppState): void {
  currentState = state;
  if (tray) {
    tray.setImage(createTrayIcon());
    tray.setToolTip(
      state === "idle"
        ? `StayFree - Ready (Hold ${holdKeyLabel} to dictate)`
        : state === "recording"
          ? "StayFree - Recording..."
          : "StayFree - Processing...",
    );
  }
}

// True when the currently visible Space is a native fullscreen-app Space, where
// the Dock is absent. Set by the space-watcher helper (see startSpaceWatcher).
// workArea is blind to this, so we track it separately and drop the widget to
// the true screen bottom in that case.
let spaceIsFullscreen = false;

// Bounds for the widget window: centered horizontally, bottom edge flush with
// the bottom of the usable area. Normally that's the work-area bottom (the dock
// top, or the screen bottom when the dock is hidden/auto-hidden — workArea
// already accounts for both). In a fullscreen Space workArea still reports the
// desktop's dock-inclusive value, so there we use the full display bottom
// instead. The pill inside is anchored to the bottom via CSS padding, so it
// visually sits ~8px above that edge and grows upward as it morphs — the native
// window itself never resizes.
function getWidgetWindowBounds(): Electron.Rectangle {
  const display = screen.getPrimaryDisplay();
  const workArea = display.workArea;
  const bounds = display.bounds;
  const x = Math.round(
    workArea.x + (workArea.width - WIDGET_WINDOW_WIDTH) / 2,
  );
  // In a fullscreen Space, sit at the true screen bottom; otherwise at the
  // work-area bottom (which sits above the dock when it's present).
  const bottom = spaceIsFullscreen
    ? bounds.y + bounds.height
    : workArea.y + workArea.height;
  const y = Math.round(bottom - WIDGET_WINDOW_HEIGHT);
  return {
    x,
    y,
    width: WIDGET_WINDOW_WIDTH,
    height: WIDGET_WINDOW_HEIGHT,
  };
}

// Wispr-style follow: when the dock is shown/hidden (or the screen changes),
// macOS's workArea changes, so the widget must slide to the new bottom edge.
// The vertical move is hand-tweened (ease-out cubic over ~250ms) rather than a
// native animated setBounds — the native animation is exactly what glitched the
// morph, so we drive it ourselves for a butter-smooth slide. X/width shifts
// (resolution changes only) are applied instantly; just the Y slides.
const WIDGET_REPOSITION_MS = 250;
let widgetTweenTimer: ReturnType<typeof setInterval> | null = null;

function repositionWidget(animate: boolean): void {
  if (!widgetWindow || widgetWindow.isDestroyed()) return;

  const target = getWidgetWindowBounds();
  const current = widgetWindow.getBounds();

  // Apply any horizontal / size change instantly (rare: resolution change).
  if (
    current.x !== target.x ||
    current.width !== target.width ||
    current.height !== target.height
  ) {
    widgetWindow.setBounds({
      x: target.x,
      y: current.y,
      width: target.width,
      height: target.height,
    });
  }

  if (widgetTweenTimer) {
    clearInterval(widgetTweenTimer);
    widgetTweenTimer = null;
  }

  const startY = widgetWindow.getBounds().y;
  const endY = target.y;
  if (startY === endY) return;

  if (!animate) {
    widgetWindow.setBounds({
      x: target.x,
      y: endY,
      width: target.width,
      height: target.height,
    });
    return;
  }

  const startTs = Date.now();
  widgetTweenTimer = setInterval(() => {
    if (!widgetWindow || widgetWindow.isDestroyed()) {
      if (widgetTweenTimer) clearInterval(widgetTweenTimer);
      widgetTweenTimer = null;
      return;
    }
    const t = Math.min(1, (Date.now() - startTs) / WIDGET_REPOSITION_MS);
    const eased = 1 - Math.pow(1 - t, 3); // ease-out cubic
    const y = Math.round(startY + (endY - startY) * eased);
    const b = widgetWindow.getBounds();
    widgetWindow.setBounds({ x: b.x, y, width: b.width, height: b.height });
    if (t >= 1) {
      if (widgetTweenTimer) clearInterval(widgetTweenTimer);
      widgetTweenTimer = null;
    }
  }, 16);
}

// --- Space watcher: detect fullscreen-app Spaces (dock absent) ---
// macOS fires no display event and workArea stays dock-inclusive when the active
// Space becomes a fullscreen app, so a tiny native helper (native/space-watcher.m)
// observes NSWorkspace space changes and reads the real Current Space type. It
// prints "1" (fullscreen) / "0" (normal) on stdout. Runs as a separate, crash-
// isolated process; if it fails we simply fall back to workArea behaviour.
let spaceWatcher: ChildProcess | null = null;

function startSpaceWatcher(): void {
  if (!isMac) return;
  // Packaged: shipped as an extraResource in Contents/Resources (outside asar).
  // Dev: copied by CopyWebpackPlugin next to the main bundle under assets/.
  const binPath = app.isPackaged
    ? path.join(process.resourcesPath, "space-watcher")
    : path.join(__dirname, "assets", "space-watcher");
  if (!fs.existsSync(binPath)) {
    console.error("[SpaceWatcher] helper not found at", binPath);
    return;
  }
  try {
    // CopyWebpackPlugin may not preserve the exec bit — ensure it's runnable.
    fs.chmodSync(binPath, 0o755);
  } catch {
    /* best-effort */
  }

  try {
    spaceWatcher = spawn(binPath, [], { stdio: ["ignore", "pipe", "pipe"] });
  } catch (err) {
    console.error("[SpaceWatcher] spawn failed:", err);
    spaceWatcher = null;
    return;
  }

  let buf = "";
  spaceWatcher.stdout?.on("data", (chunk: Buffer) => {
    buf += chunk.toString();
    let nl: number;
    while ((nl = buf.indexOf("\n")) !== -1) {
      const line = buf.slice(0, nl).trim();
      buf = buf.slice(nl + 1);
      if (line !== "0" && line !== "1") continue;
      const fullscreen = line === "1";
      if (fullscreen === spaceIsFullscreen) continue;
      spaceIsFullscreen = fullscreen;
      console.log(
        `[SpaceWatcher] space -> ${fullscreen ? "fullscreen (dock absent)" : "normal (dock present)"}`,
      );
      repositionWidget(true);
    }
  });

  spaceWatcher.stderr?.on("data", (chunk: Buffer) => {
    console.error("[SpaceWatcher]", chunk.toString().trim());
  });

  spaceWatcher.on("exit", (code, signal) => {
    console.error(`[SpaceWatcher] helper exited (code=${code} signal=${signal})`);
    spaceWatcher = null;
    // Fail-safe: leave the widget wherever it is. We do not auto-restart to
    // avoid a crash loop; the widget still follows the dock via workArea.
  });

  spaceWatcher.on("error", (err) => {
    console.error("[SpaceWatcher] process error:", err);
  });
}

function stopSpaceWatcher(): void {
  if (spaceWatcher) {
    spaceWatcher.kill();
    spaceWatcher = null;
  }
}

// An ultra-short tap records nothing meaningful — there is nothing to
// transcribe, so the widget must NOT show a "thinking" state at all: it goes
// straight from recording back to idle and the ASR round-trip is skipped.
const MIN_MEANINGFUL_RECORDING_MS = 300;

function isShortTap(): boolean {
  return (
    !activeRecordingSession ||
    (activeRecordingSession.stopTs ?? Date.now()) - activeRecordingSession.startTs <
      MIN_MEANINGFUL_RECORDING_MS
  );
}

// Wispr-style pacing: an ultra-fast pipeline (empty audio fails ASR in ~25ms)
// would flash processing → idle within a couple of frames, which reads as a
// glitch. Hold the processing look for at least this long before going idle.
// Any newer non-idle state (a fresh recording) cancels the hold instantly.
const MIN_PROCESSING_VISIBLE_MS = 350;
let widgetProcessingSince = 0;
let widgetPendingIdleTimer: ReturnType<typeof setTimeout> | null = null;

function sendWidgetState(
  state: WidgetUiState,
  opts?: { message?: string; pipelineId?: number | null },
): void {
  if (!widgetWindow || widgetWindow.isDestroyed()) return;

  if (widgetPendingIdleTimer) {
    clearTimeout(widgetPendingIdleTimer);
    widgetPendingIdleTimer = null;
  }

  if (state === "processing") {
    if (!widgetProcessingSince) widgetProcessingSince = Date.now();
  } else if (state === "idle" && widgetProcessingSince) {
    const shownFor = Date.now() - widgetProcessingSince;
    if (shownFor < MIN_PROCESSING_VISIBLE_MS) {
      widgetPendingIdleTimer = setTimeout(() => {
        widgetPendingIdleTimer = null;
        widgetProcessingSince = 0;
        if (widgetWindow && !widgetWindow.isDestroyed()) {
          const idlePayload: WidgetStatePayload = { state: "idle", pipelineId: null };
          // Track at the SEND, not when the deferral was scheduled — the
          // processing pill is still on screen until this fires.
          currentWidgetUiState = "idle";
          widgetWindow.webContents.send("widget-state", idlePayload);
        }
      }, MIN_PROCESSING_VISIBLE_MS - shownFor);
      return;
    }
    widgetProcessingSince = 0;
  } else {
    // recording/error states: fresh cycle, forget the previous processing stamp
    widgetProcessingSince = 0;
  }

  // No native resize — the renderer morphs the pill purely in CSS.
  const payload: WidgetStatePayload = {
    state,
    message: opts?.message,
    pipelineId: opts?.pipelineId ?? null,
  };
  // Keep main's hit-test rect in step with what the renderer is about to draw
  // (see currentWidgetUiState's doc comment for the one accepted mismatch).
  currentWidgetUiState = state;
  widgetWindow.webContents.send("widget-state", payload);
}

function createRecordingSession(): RecordingSession {
  return {
    sessionId: `rec-${Date.now()}-${Math.random().toString(16).slice(2, 8)}`,
    startTs: Date.now(),
    stopTs: null,
    pcmChunks: [],
    chunkCount: 0,
    chunkBytes: 0,
    energySummary: null,
    pipelineId: null,
    pipelineTimer: null,
  };
}

function startRecordingSession(): RecordingSession {
  activeRecordingSession = createRecordingSession();
  return activeRecordingSession;
}

function stopRecordingSession(): void {
  if (activeRecordingSession) {
    activeRecordingSession.stopTs = Date.now();
  }
}

function clearRecordingSession(expectedSession?: RecordingSession): void {
  if (expectedSession && activeRecordingSession !== expectedSession) return;
  activeRecordingSession = null;
}

function resetAfterRecorderError(sessionId: string, message: string): void {
  const session = activeRecordingSession;
  if (!session || session.sessionId !== sessionId) {
    console.log(`[Recorder] Ignoring stale error for session=${sessionId}`);
    return;
  }

  console.error(`[Recorder] ${message} (session=${sessionId})`);
  // Capture failures must be visible too (FIX 7 — same D1 principle as ASR
  // failures): surface the recorder's user-safe message through the widget
  // error mechanism (same auto-revert pill) before resetting to idle. The
  // trailing "idle" send below is safe — the widget ignores idle while its
  // error pill's own revert timer is pending.
  sendWidgetState("error", { message, pipelineId: session.pipelineId });
  if (session.pipelineTimer) {
    clearTimeout(session.pipelineTimer);
    if (processingTimer === session.pipelineTimer) {
      processingTimer = null;
    }
    session.pipelineTimer = null;
  }
  if (activePipelineId === session.pipelineId) {
    activePipelineId = null;
  }

  clearRecordingSession(session);
  activeRecordingSource = null;
  isProcessing = false;
  updateTrayState("idle");
  sendWidgetState("idle");
}

function beginRecording(
  source: Exclude<RecordingSource, null>,
  widgetState: Extract<WidgetUiState, "recording-hotkey" | "recording-click">,
): void {
  if (!recorderWindow) return;

  activeRecordingSource = source;
  lastRecordingSource = source;
  updateTrayState("recording");
  sendWidgetState(widgetState);

  const session = startRecordingSession();

  // `true` here is the locked renderer wire arg name "hindiMode" (see
  // recorder.ts / preload.ts onStartRecording) — deliberately left
  // unrenamed (D6: renderer wire names stay untouched; only main-side
  // "Hindi" naming was recast). It now just means "stream PCM16 to main"
  // for the whisper pipeline — there is only one transcription path.
  recorderWindow.webContents.send("start-recording", true, session.sessionId);

  // No connection setup needed here: the whisper sidecar is a warm local
  // process (started once at app launch — see app.on("ready") — and kept
  // alive across recordings via crash auto-restart). ensureReady() is
  // called from transcribePcm() itself when the ASR step actually begins.
}

function armPipelineDeadline(session: RecordingSession): number {
  const pipelineId = ++pipelineSequence;
  activePipelineId = pipelineId;
  session.pipelineId = pipelineId;

  if (processingTimer) clearTimeout(processingTimer);
  const timer = setTimeout(() => {
    if (activePipelineId === pipelineId) {
      console.error(
        `[Pipeline] ✗ Processing timeout after ${PROCESSING_TIMEOUT_MS}ms — force resetting`,
      );
      // No in-flight network operation to abort here: transcribePcm()'s own
      // AbortController self-terminates within ASR_REQUEST_TIMEOUT_MS
      // regardless of this reset, and its result is discarded by the stale
      // activePipelineId check once it settles.
      sendWidgetState("error", {
        message: "Transcription took too long. Please try again.",
        pipelineId,
      });
      clearRecordingSession(session);
      activeRecordingSource = null;
      activePipelineId = null;
      isProcessing = false;
      updateTrayState("idle");
      sendWidgetState("idle");
    }
    if (processingTimer === timer) processingTimer = null;
    session.pipelineTimer = null;
  }, PROCESSING_TIMEOUT_MS);

  session.pipelineTimer = timer;
  processingTimer = timer;
  return pipelineId;
}

/** Shrunk per D8 — transcriber.ts's own mapError() already classifies every
 * ASR-specific failure into a PipelineError before it ever reaches here.
 * This only needs to pass those through and give a generic fallback to any
 * truly unexpected error from elsewhere in the pipeline (save/paste/etc). */
function mapPipelineError(error: unknown): PipelineError {
  if (error instanceof PipelineError) return error;
  return new PipelineError(
    "ASR_FAILED",
    "Something went wrong during transcription. Please try again.",
  );
}

function createWidgetWindow(): void {
  if (widgetWindow) return;

  widgetWindow = new BrowserWindow({
    ...getWidgetWindowBounds(),
    show: false,
    frame: false,
    transparent: true,
    hasShadow: false,
    resizable: false,
    minimizable: false,
    maximizable: false,
    fullscreenable: false,
    skipTaskbar: true,
    alwaysOnTop: true,
    movable: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
      contextIsolation: true,
      // The widget is never focused; if Chromium ever marks it backgrounded/
      // occluded it throttles rAF to <1Hz and every animation (framer springs,
      // waveform) freezes mid-flight. Never throttle this window.
      backgroundThrottling: false,
    },
  });

  widgetWindow.setAlwaysOnTop(true, "floating");
  widgetWindow.setVisibleOnAllWorkspaces(true, {
    visibleOnFullScreen: true,
  });

  // The window is much larger than the visible pill, so it is click-through by
  // default; the hit-test poller below flips it interactive only while the
  // cursor is genuinely inside the pill's (padded) rect. Reset both tracked
  // values here so a recreated window never inherits stale state.
  currentWidgetUiState = "idle";
  widgetIgnoresMouse = true;
  widgetWindow.setIgnoreMouseEvents(true);

  widgetWindow.loadURL(`${MAIN_WINDOW_WEBPACK_ENTRY}#widget`);

  widgetWindow.once("ready-to-show", () => {
    if (widgetWindow) {
      widgetWindow.showInactive();
      sendWidgetState("idle");
    }
  });

  // Cursor-vs-pill hit-testing runs for as long as the window exists.
  startWidgetHitPoll();

  widgetWindow.on("closed", () => {
    stopWidgetHitPoll();
    widgetWindow = null;
  });
}

// Export for use by other modules later
export { updateTrayState, currentState };
export type { AppState };

// --- Context Menu ---

function buildContextMenu(): Menu {
  return Menu.buildFromTemplate([
    {
      label: `StayFree v${app.getVersion()}`,
      enabled: false,
    },
    { type: "separator" },
    {
      label: "Paste Last Transcript",
      accelerator: fallbackPasteShortcut,
      click: async () => {
        const lastTranscript = store.get("lastTranscript") as string;
        if (lastTranscript) {
          await pasteText(lastTranscript);
        }
      },
    },
    { type: "separator" },
    {
      label: "Settings...",
      accelerator: settingsShortcut,
      click: () => {
        openSettingsWindow();
      },
    },
    { type: "separator" },
    {
      label: "Quit StayFree",
      accelerator: quitShortcut,
      click: () => {
        app.quit();
      },
    },
  ]);
}

// --- Recorder Window (Hidden) ---

function createRecorderWindow(): void {
  recorderWindow = new BrowserWindow({
    width: 400,
    height: 300,
    show: false, // Hidden window
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
      contextIsolation: true,
      // Hidden windows are throttled to ~1fps by default, which would stall the
      // live audio-level meter that drives the widget waveform. Keep it running.
      backgroundThrottling: false,
    },
  });

  recorderWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);


  recorderWindow.on("closed", () => {
    recorderWindow = null;
  });

  console.log("[StayFree] Hidden recorder window created");
}

// --- Settings / Dashboard Window ---

function applyMacDockIcon(): void {
  if (!isMac) return;

  const iconPath = path.join(__dirname, "assets", "appIcon.png");
  const icon = nativeImage.createFromPath(iconPath);
  if (icon.isEmpty()) {
    console.warn(`[Branding] Could not load Dock icon from ${iconPath}`);
    return;
  }

  app.dock.setIcon(icon);
  console.log("[Branding] StayFree Dock icon applied");
}

async function showMacDock(): Promise<void> {
  if (!isMac) return;
  await app.dock.show();
  // Showing the generic Electron.app can restore its bundled icon in
  // development, so apply StayFree only after the Dock is visible.
  applyMacDockIcon();
}

function openSettingsWindow(): void {
  if (settingsWindow) {
    settingsWindow.focus();
    return;
  }

  // Show dock so the dashboard window is discoverable
  if (isMac) {
    void showMacDock();
  }

  const settingsWindowOptions: Electron.BrowserWindowConstructorOptions = {
    width: 1400,
    height: 900,
    title: "StayFree",
    minWidth: 900,
    minHeight: 650,
    show: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
      contextIsolation: true,
    },
  };

  if (isMac) {
    settingsWindowOptions.titleBarStyle = "hiddenInset";
    settingsWindowOptions.trafficLightPosition = { x: 18, y: 25 };
  }

  settingsWindow = new BrowserWindow(settingsWindowOptions);

  settingsWindow.loadURL(`${MAIN_WINDOW_WEBPACK_ENTRY}#settings`);

  settingsWindow.once("ready-to-show", () => {
    settingsWindow.show();
  });

  settingsWindow.on("closed", () => {
    settingsWindow = null;
    if (isMac) {
      app.dock.hide();
    }
  });
}

function getInputAutomationStatus(): boolean | null {
  if (!isMac) return null;
  return systemPreferences.isTrustedAccessibilityClient(false);
}

// --- Onboarding Window ---

function needsOnboarding(): boolean {
  const onboardingComplete = store.get("onboardingComplete");
  const micStatus = systemPreferences.getMediaAccessStatus("microphone");
  const inputAutomation = getInputAutomationStatus();
  const forceOnboarding =
    !app.isPackaged && process.env.STAYFREE_FORCE_ONBOARDING === "1";
  const onboardingReady = isMac
    ? micStatus === "granted" && inputAutomation
    : micStatus === "granted";

  console.log(
    `[Onboarding] Startup state: platform=${process.platform}, packaged=${app.isPackaged}, completed=${onboardingComplete}, forced=${forceOnboarding}, microphone=${micStatus}, accessibility=${inputAutomation ?? "not-required"}`,
  );

  if (forceOnboarding) {
    console.log("[Onboarding] Forced open for development verification");
    return true;
  }

  if (onboardingComplete && onboardingReady) {
    return false;
  }

  if (onboardingComplete) {
    // Even if onboarding was completed, re-show if permissions were revoked
    console.log(
      "[Onboarding] Permissions revoked since last onboarding - re-showing",
    );
  }
  return true;
}

function showOnboardingWindow(): void {
  if (onboardingWindow) {
    onboardingWindow.focus();
    return;
  }

  // Temporarily show dock so the onboarding window is discoverable
  if (isMac) {
    void showMacDock();
  }

  onboardingWindow = new BrowserWindow({
    width: 820,
    height: 580,
    title: "Welcome to StayFree",
    resizable: false,
    minimizable: false,
    maximizable: false,
    fullscreenable: false,
    show: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
      contextIsolation: true,
    },
    ...(isMac
      ? {
          titleBarStyle: "hiddenInset",
          trafficLightPosition: { x: 18, y: 18 },
          backgroundColor: "#f4f2ec",
        }
      : {}),
  });

  // Hash routing: renderer.ts checks window.location.hash to decide what to render
  onboardingWindow.loadURL(`${MAIN_WINDOW_WEBPACK_ENTRY}#onboarding`);

  onboardingWindow.once("ready-to-show", () => {
    onboardingWindow.show();
  });

  onboardingWindow.on("closed", () => {
    onboardingWindow = null;
    // Hide dock again after onboarding closes
    if (isMac) {
      app.dock.hide();
    }
  });

  console.log("[Onboarding] Window created");
}

// --- Permission IPC Handlers ---

function registerPermissionHandlers(): void {
  ipcMain.handle("check-permissions", () => {
    const mic = systemPreferences.getMediaAccessStatus("microphone");
    const inputAutomation = getInputAutomationStatus();
    return { mic, inputAutomation, platform: process.platform };
  });

  ipcMain.handle("request-mic-permission", async () => {
    if (isMac) {
      return systemPreferences.askForMediaAccess("microphone");
    }
    if (isWindows) {
      await shell.openExternal("ms-settings:privacy-microphone");
      // User must grant permission manually in Settings — renderer re-checks via check-permissions polling
      return false;
    }
    return false;
  });

  ipcMain.on("open-accessibility-settings", () => {
    if (isMac) {
      // Prompt the system dialog
      systemPreferences.isTrustedAccessibilityClient(true);
      shell.openExternal(
        "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility",
      );
      return;
    }

    if (isWindows) {
      shell.openExternal("ms-settings:easeofaccess-keyboard");
    }
  });

  ipcMain.on("open-keyboard-settings", () => {
    if (isMac) {
      shell.openExternal("x-apple.systempreferences:com.apple.preference.keyboard");
      return;
    }
    if (isWindows) {
      shell.openExternal("ms-settings:typing");
    }
  });

  ipcMain.on("complete-onboarding", () => {
    store.set("onboardingComplete", true);
    console.log("[Onboarding] Completed");
    if (isMac) {
      getHotkeyManager().start();
    }
    if (onboardingWindow) {
      onboardingWindow.close();
    }
  });
}

// --- Settings IPC Handlers ---

function registerSettingsHandlers(): void {
  ipcMain.handle("get-settings", () => {
    return {
      selectedMicId: store.get("selectedMicId"),
      soundEnabled: store.get("soundEnabled"),
    };
  });

  ipcMain.handle("download-audio-file", async (_event, filename: string) => {
    return await copyAudioToDownloads(filename);
  });

  ipcMain.on("save-selected-mic", (_event, deviceId: string) => {
    store.set("selectedMicId", deviceId);
    console.log(`[Settings] Microphone saved: ${deviceId || "system default"}`);
    if (recorderWindow && !recorderWindow.isDestroyed()) {
      recorderWindow.webContents.send("selected-mic-changed", deviceId);
    }
  });

  ipcMain.on("save-sound-enabled", (_event, enabled: boolean) => {
    store.set("soundEnabled", enabled);
    console.log(`[Settings] Sound ${enabled ? "enabled" : "disabled"}`);
  });

  ipcMain.handle("get-transcription-history", () => {
    return store.get("transcriptionHistory");
  });

  ipcMain.handle("get-total-words-spoken", () => {
    return store.get("totalWordsSpoken");
  });

  ipcMain.on("clear-transcription-history", () => {
    cleanupAllAudioFiles();
    store.set("transcriptionHistory", []);
    // Note: totalWordsSpoken is intentionally NOT reset on clear — it is a
    // permanent lifetime counter unaffected by history management.
    console.log("[Settings] History cleared (audio files deleted)");
  });

  ipcMain.handle("get-app-version", () => {
    return app.getVersion();
  });
}

// --- Widget IPC Handlers ---

function registerWidgetHandlers(): void {
  ipcMain.on("recorder-started", (event, sessionId: string) => {
    if (
      !recorderWindow ||
      recorderWindow.isDestroyed() ||
      event.sender !== recorderWindow.webContents
    ) {
      return;
    }
    if (activeRecordingSession?.sessionId === sessionId) {
      console.log(`[Recorder] Capture confirmed (session=${sessionId})`);
    }
  });

  ipcMain.on(
    "recorder-error",
    (event, sessionId: string, message: string) => {
      if (
        !recorderWindow ||
        recorderWindow.isDestroyed() ||
        event.sender !== recorderWindow.webContents
      ) {
        return;
      }
      resetAfterRecorderError(sessionId, message);
    },
  );

  ipcMain.on("widget-start-recording", () => {
    if (isProcessing || currentState !== "idle") return;
    if (!recorderWindow) {
      console.error("[Widget] Recorder window unavailable");
      return;
    }

    beginRecording("widget", "recording-click");
  });

  ipcMain.on("widget-stop-recording", () => {
    if (currentState !== "recording" || activeRecordingSource !== "widget") {
      return;
    }
    if (!recorderWindow) {
      console.error("[Widget] Recorder window unavailable");
      activeRecordingSource = null;
      updateTrayState("idle");
      sendWidgetState("idle");
      return;
    }

    const session = activeRecordingSession;
    activeRecordingSource = null;
    stopRecordingSession();
    if (isShortTap()) {
      console.log("[Widget] Short tap — nothing to transcribe, going idle");
      updateTrayState("idle");
      sendWidgetState("idle");
    } else {
      updateTrayState("processing");
      sendWidgetState("processing");
      if (session) armPipelineDeadline(session);
    }
    if (session) {
      recorderWindow.webContents.send("stop-recording", session.sessionId);
    }
  });

  ipcMain.on("widget-cancel-recording", () => {
    if (currentState !== "recording" || activeRecordingSource !== "widget") {
      return;
    }
    if (!recorderWindow) {
      activeRecordingSource = null;
      updateTrayState("idle");
      sendWidgetState("idle");
      return;
    }

    const session = activeRecordingSession;
    activeRecordingSource = null;
    clearRecordingSession(session ?? undefined);
    if (session) {
      recorderWindow.webContents.send("cancel-recording", session.sessionId);
    }
    updateTrayState("idle");
    sendWidgetState("idle");
  });

  // Live mic level from the recorder → drives the widget waveform in real time.
  ipcMain.on("audio-level", (_event, level: number) => {
    if (!widgetWindow || widgetWindow.isDestroyed()) return;
    widgetWindow.webContents.send("widget-audio-level", level);
  });

  ipcMain.on("widget-open-settings", () => {
    openSettingsWindow();
  });

}

// --- App Lifecycle ---

app.on("ready", () => {
  // One-time credential purge — see purgeLegacySarvamApiKey() doc comment.
  purgeLegacySarvamApiKey();
  // One-time migration: seed cumulative word count from pre-existing history.
  seedWordCountFromHistory();

  // Hide dock icon on macOS - this is a tray-only app
  if (isMac) {
    applyMacDockIcon();
    app.dock.hide();
  }

  // Register IPC handlers (needed before any window loads)
  registerPermissionHandlers();
  registerSettingsHandlers();
  registerWidgetHandlers();

  // Create system tray
  tray = new Tray(createTrayIcon());
  tray.setContextMenu(buildContextMenu());
  tray.setToolTip(`StayFree - Ready (Hold ${holdKeyLabel} to dictate)`);
  tray.on("click", () => {
    openSettingsWindow();
  });

  console.log(
    "[StayFree] Running in system tray. Right-click tray icon for menu.",
  );

  // Create hidden recorder window (for Web Audio API access)
  createRecorderWindow();
  createWidgetWindow();

  // Follow the dock: when it shows/hides (or the display changes), macOS's
  // workArea shifts. Slide the widget to the new bottom edge so it always sits
  // just above the dock — or just above the screen bottom when the dock is gone.
  screen.on("display-metrics-changed", (_event, _display, changedMetrics) => {
    if (
      changedMetrics.includes("workArea") ||
      changedMetrics.includes("bounds")
    ) {
      repositionWidget(true);
    }
  });

  // Watch for fullscreen-app Space changes (dock absent there) and reposition.
  startSpaceWatcher();


  // Keep-warm: start the local whisper sidecar now so the model is already
  // loaded by the time a dictation happens. Never awaited — must not block
  // onboarding/hotkey/recorder setup (D3). ensureReady() inside
  // transcribePcm() covers the case where a dictation races this.
  // Rejection is expected when assets aren't installed (or a quit races the
  // warm-up) — log quietly (FIX 6), never let it reach the emergency
  // uncaughtException handler. No state mutation needed: start() already
  // left the server "unavailable" and the first dictation surfaces the
  // actionable ENGINE_UNAVAILABLE error (D9.6).
  getWhisperServer()
    .start()
    .catch((err: unknown) => {
      console.warn(
        `[Whisper] Warm-up start failed (engine unavailable until fixed): ${
          err instanceof Error ? err.message : String(err)
        }`,
      );
    });

  // Show onboarding if first launch or permissions missing
  if (needsOnboarding()) {
    showOnboardingWindow();
  }

  // Initialize hotkey manager (hold key push-to-talk)
  const hotkeyManager = getHotkeyManager();

  hotkeyManager.on("recording-start", () => {
    if (isProcessing || currentState !== "idle") return;
    if (!recorderWindow) {
      console.error("[Main] Recorder window unavailable");
      return;
    }

    console.log("[Main] Hotkey pressed - starting recording");
    beginRecording("hotkey", "recording-hotkey");
  });

  hotkeyManager.on("recording-stop", () => {
    if (currentState !== "recording" || activeRecordingSource !== "hotkey") {
      return;
    }
    if (!recorderWindow) {
      console.error("[Main] Recorder window unavailable");
      activeRecordingSource = null;
      updateTrayState("idle");
      sendWidgetState("idle");
      return;
    }

    console.log("[Main] Hotkey released - stopping recording");
    // Go directly to "processing" - avoids idle flash between recording and processing
    const session = activeRecordingSession;
    activeRecordingSource = null;
    stopRecordingSession();
    if (isShortTap()) {
      console.log("[Main] Short tap — nothing to transcribe, going idle");
      updateTrayState("idle");
      sendWidgetState("idle");
    } else {
      updateTrayState("processing");
      sendWidgetState("processing");
      if (session) armPipelineDeadline(session);
    }

    // Tell recorder window to stop and send audio
    if (session) {
      recorderWindow.webContents.send("stop-recording", session.sessionId);
    }
  });

  // Start listening for hotkeys
  if (!isMac || getInputAutomationStatus()) {
    hotkeyManager.start();
  } else {
    console.log(
      "[Hotkey] Waiting for Accessibility permission before starting listener",
    );
  }

  // Register fallback hotkey to paste last transcript
  const fallbackRegistered = globalShortcut.register(fallbackPasteShortcut, async () => {
    const lastTranscript = store.get("lastTranscript") as string;
    if (lastTranscript) {
      console.log("[Main] Fallback hotkey: pasting last transcript");
      const pasted = await pasteText(lastTranscript);
      if (!pasted) {
        console.error("[Main] Fallback paste failed");
      }
    } else {
      console.log("[Main] Fallback hotkey: no last transcript to paste");
    }
  });
  if (!fallbackRegistered) {
    console.warn(`[Main] Failed to register fallback shortcut: ${fallbackPasteShortcut}`);
  }

  // IPC Handler: accumulate PCM16 chunks locally. Accumulate-only — v1 scope
  // is full-buffer record->stop->transcribe (see plan §1); the complete
  // buffer is sent to the whisper sidecar as one WAV once recording stops.
  // Channel name kept as "audio-chunk-stream" — locked renderer wire name (D6).
  ipcMain.on("audio-chunk-stream", (_event, chunk: Buffer, sessionId: string) => {
    const session = activeRecordingSession;
    if (!session || session.sessionId !== sessionId) return;

    session.pcmChunks.push(chunk);
    session.chunkCount += 1;
    session.chunkBytes += chunk.length;
  });

  ipcMain.on(
    "audio-stream-stats",
    (_event, stats: AudioStreamStatsPayload, sessionId: string) => {
      if (!activeRecordingSession || activeRecordingSession.sessionId !== sessionId) {
        return;
      }
      activeRecordingSession.energySummary = stats;
      activeRecordingSession.chunkCount = Math.max(
        activeRecordingSession.chunkCount,
        stats.chunkCount,
      );
      activeRecordingSession.chunkBytes = Math.max(
        activeRecordingSession.chunkBytes,
        stats.pcmBytes,
      );
    },
  );

  // IPC Handler: Receive audio blob from renderer — full pipeline
  ipcMain.on("audio-captured", async (
    _event,
    audioData: Buffer,
    sessionId: string,
  ) => {
    // Guard: prevent concurrent pipeline runs
    if (isProcessing) {
      console.warn("[Pipeline] Already processing - ignoring new audio");
      return;
    }

    // A short tap goes idle instantly, so a NEW recording may already be
    // running by the time the previous tap's audio blob lands here. That blob
    // belongs to the superseded recording — drop it, don't touch live state.
    if (currentState === "recording") {
      console.log("[Pipeline] Stale audio from a superseded recording — dropping");
      return;
    }
    const session = activeRecordingSession;
    if (!session || session.sessionId !== sessionId) {
      console.log(`[Pipeline] Stale audio for session=${sessionId} — dropping`);
      return;
    }
    isProcessing = true;

    // Short-tap fast path: nothing meaningful was recorded (see recording-stop
    // handlers, which already kept the widget out of the processing state).
    // Skip the whole pipeline — no ASR round-trip, settle to idle silently.
    if (isShortTap()) {
      console.log("[Pipeline] Short tap — skipping pipeline");
      clearRecordingSession();
      activeRecordingSource = null;
      isProcessing = false;
      if (processingTimer) {
        clearTimeout(processingTimer);
        processingTimer = null;
      }
      updateTrayState("idle");
      sendWidgetState("idle");
      return;
    }

    // The deadline starts on key/button release, before MediaRecorder finishes
    // assembling its blob. Fall back to arming here only for defensive safety.
    const pipelineId = session.pipelineId ?? armPipelineDeadline(session);
    const thisPipelineTimer = session.pipelineTimer;

    // Capture source before any async work (activeRecordingSource may change)
    const capturedSource = lastRecordingSource;

    const pipelineStart = Date.now();
    console.log(`\n[Pipeline] ═══ START ═══ source=${capturedSource} (${audioData.length} bytes)`);

    // Tray should already be "processing" from recording-stop handler
    updateTrayState("processing");
    sendWidgetState("processing");

    try {
      // ── DICTATION PIPELINE ───────────────────────────────────────
      // --- Save audio to userData ---
      const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
      const audioFilename = await saveAudioFile(audioData, timestamp);
      if (activePipelineId !== pipelineId) {
        throw new PipelineError(
          "ASR_TIMEOUT",
          "Transcription was cancelled after reaching its time limit.",
        );
      }

      // --- Step 1: ASR (local whisper.cpp sidecar) ---
      const stats = session.energySummary;
      const capturedAudioMs = Math.round(session.chunkBytes / 32);
      const recordingWallMs =
        session.stopTs && session.startTs
          ? Math.max(0, session.stopTs - session.startTs)
          : null;
      console.log(
        `[Whisper] session=${session.sessionId} chunks=${session.chunkCount} bytes=${session.chunkBytes} capturedMs=${capturedAudioMs} wallMs=${recordingWallMs ?? "unknown"} localSpeech=${stats?.hasSpeech ?? "unknown"} borderline=${stats?.isBorderlineSpeech ?? "unknown"} voicedMs=${stats?.voicedMs ?? 0}`,
      );

      const asrStart = Date.now();
      // The staleness callback (FIX 8) lets transcribePcm skip its engine
      // restart + second attempt once this pipeline's deadline has fired.
      const transcript = await transcribePcm(
        Buffer.concat(session.pcmChunks),
        () => activePipelineId === pipelineId,
      );
      const L_asr = Date.now() - asrStart;

      if (activePipelineId !== pipelineId) {
        throw new PipelineError(
          "ASR_TIMEOUT",
          "Transcription was cancelled after reaching its time limit.",
        );
      }

      console.log(`[Pipeline] ✓ ASR (${L_asr}ms): "${transcript}"`);

      // --- Step 2: Raw paste (no formatting) ---
      let formattedText = transcript;

      // Ensure the text ends with a space so consecutive dictates don't stick together
      if (!/\s$/.test(formattedText)) {
        formattedText += " ";
      }

      // Store for fallback paste shortcut
      store.set("lastTranscript", formattedText);

      // Save to transcription history (keep last 50)
      const history = store.get("transcriptionHistory") as TranscriptionEntry[];
      history.unshift({
        text: formattedText,
        rawText: transcript,
        timestamp: Date.now(),
        durationMs: Date.now() - pipelineStart,
        audioFilePath: audioFilename ?? undefined,
      });
      while (history.length > 50) {
        const removed = history.pop();
        if (removed?.audioFilePath) {
          deleteAudioFile(removed.audioFilePath);
        }
      }
      store.set("transcriptionHistory", history);

      // Accumulate cumulative word count — persists independently of the
      // 50-entry history cap. Words are never subtracted when old entries
      // are pruned; this counter only ever grows.
      const newWords = formattedText.trim().split(/\s+/).filter(Boolean).length;
      const prevTotal = store.get("totalWordsSpoken") as number;
      store.set("totalWordsSpoken", prevTotal + newWords);

      // Notify dashboard to refresh
      if (settingsWindow && !settingsWindow.isDestroyed()) {
        settingsWindow.webContents.send("transcription-history-updated");
      }

      // --- Step 3: Paste ---
      if (activePipelineId !== pipelineId) {
        throw new PipelineError(
          "ASR_TIMEOUT",
          "Transcription was cancelled after reaching its time limit.",
        );
      }
      const pasteStart = Date.now();
      const pasted = await pasteText(formattedText);
      const L_paste = Date.now() - pasteStart;

      if (pasted) {
        console.log(`[Pipeline] ✓ Paste (${L_paste}ms)`);
      } else {
        console.error(
          `[Pipeline] ✗ Paste failed (${L_paste}ms) - text in clipboard for manual ${pasteShortcutLabel}`,
        );
      }

      // --- Timing Summary ---
      const L_total = Date.now() - pipelineStart;
      console.log(
        `[Pipeline] ═══ DONE ═══ L_asr=${L_asr}ms | L_paste=${L_paste}ms | L_total=${L_total}ms`,
      );
    } catch (error) {
      const L_total = Date.now() - pipelineStart;
      const mappedError = mapPipelineError(error);
      console.error(
        `[Pipeline] ✗ FATAL ${mappedError.code} after ${L_total}ms: ${mappedError.message}`,
        error,
      );
      // Final ASR failure surfaces to the widget (D1) — but never for a
      // pipeline that's already been superseded by a newer recording.
      if (activePipelineId === pipelineId) {
        sendWidgetState("error", { message: mappedError.message, pipelineId });
      }
    } finally {
      // A timed-out older pipeline must never clear a newer recording's state.
      if (activePipelineId === pipelineId) {
        clearRecordingSession(session ?? undefined);
        activeRecordingSource = null;
        activePipelineId = null;
        isProcessing = false;
        updateTrayState("idle");
        sendWidgetState("idle");
      }
      if (thisPipelineTimer && processingTimer === thisPipelineTimer) {
        clearTimeout(thisPipelineTimer);
        processingTimer = null;
        session.pipelineTimer = null;
      }
      // No re-warm needed — the whisper sidecar is a persistent local
      // process kept alive across recordings (crash auto-restart handles
      // the rest), unlike the old per-recording cloud WS connection.
    }
  });
});

// Tray app: keep running when all windows closed
app.on("window-all-closed", () => {
  // Do nothing - app lives in tray, not in windows
});

app.on("second-instance", () => {
  if (settingsWindow) {
    settingsWindow.focus();
    return;
  }
  openSettingsWindow();
});

// Guards the two-phase async quit below: the whisper sidecar needs a
// bounded async SIGTERM->grace->SIGKILL sequence (D3) before the app can
// actually exit, but Electron's before-quit is synchronous. So the first
// pass does all synchronous cleanup, then prevents default and stops the
// sidecar; once that resolves it calls app.quit() again, which re-fires
// before-quit — this time whisperStopped is already true, so it falls
// through and the quit proceeds for real.
let whisperStopped = false;

app.on("before-quit", (event) => {
  // Unregister global shortcuts
  globalShortcut.unregisterAll();

  // Stop hotkey listener
  const hotkeyManager = getHotkeyManager();
  hotkeyManager.stop();

  // Stop the native space-watcher helper
  stopSpaceWatcher();

  if (tray) {
    tray.destroy();
    tray = null;
  }

  // destroy() fires "closed", which also stops the poller — but stop it here
  // too so quitting can never leave a live interval behind (both calls are
  // idempotent).
  stopWidgetHitPoll();

  if (widgetWindow) {
    widgetWindow.destroy();
    widgetWindow = null;
  }

  if (!whisperStopped) {
    event.preventDefault();
    whisperStopped = true;
    getWhisperServer()
      .stop()
      .catch((err) => {
        console.error("[Whisper] error stopping sidecar during quit:", err);
      })
      .finally(() => {
        app.quit();
      });
  }
});
